# Generated by Django 5.0 on 2023-12-28 06:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post/images/'),
            preserve_default=False,
        ),
    ]
